# Site settings
# theme: jekyll-theme-easy-wedding
title: Beth & Chris
email: cjwilliamson109@gmail.com
url: https://chrisandbethwedding.com
description: "We're getting married and can't wait to celebrate with you!"
baseurl: ""